panda: #namespace

    # panda Task Realated parameters
    n_actions: 6 # X+/-,Y+/-,Z+/-
    n_observations: 9 # Forces, current pose
    position_ee_max: 1.0
    position_ee_min: -1.0
    base_link: 'panda_link0'
    ee_link: 'panda_EE'
    #0.0, -0.785, 0.0, -2.356, 0.0, 1.571, 0.785
    init_pos: # This has to be validated in the fetch_moveit_test.py in fetch_openai_ros_example or something that tests this pos is possible
      panda_joint1: 0.0
      panda_joint2: -0.785
      panda_joint3: 0.0
      panda_joint4: -2.356
      panda_joint5: 0.0
      panda_joint6: 1.571
      panda_joint7: 0.785

    setup_ee_pos: # This has to be validated in the fetch_moveit_test.py in fetch_openai_ros_example or something that tests this pos is possible
      x: 0.492
      y: 0.162
      z: 0.501

    goal_ee_pos: # This has to be validated in the fetch_moveit_test.py in fetch_openai_ros_example or something that tests this pos is possible
      x:  0.6 #0.37 
      y:  0.162 # 0.005
      z:  0.501 #0.59      

    position_delta: 0.02 # Increments of Decrements in the X/Y/Z positions each action step

    step_punishment: -1
    closer_reward: -1
    impossible_movement_punishement: -1
    reached_goal_reward: 50

    max_distance: 3.0 # Maximum distance from EE to the desired GOAL EE
    tolerence: 0.03 # tolerence between the goal pose
    max_away_frm_init_pose: 0.15 # allowed deviation from initial pose while moving
    
